-- Composite indexes for high-cardinality queries
-- Note: CONCURRENTLY removed — Prisma 7 wraps every migration in a transaction
-- and CREATE INDEX CONCURRENTLY cannot run inside a transaction block.
-- These indexes are non-unique and safe to build transactionally on a live table
-- (they briefly lock on the index build, which is acceptable at deploy time).

CREATE INDEX IF NOT EXISTS "Membership_businessId_isActive_idx"
  ON "Membership"("businessId", "isActive");

CREATE INDEX IF NOT EXISTS "LoyaltyTransaction_businessId_membershipId_idx"
  ON "LoyaltyTransaction"("businessId", "membershipId");

CREATE INDEX IF NOT EXISTS "StaffMember_businessId_idx"
  ON "StaffMember"("businessId");

CREATE UNIQUE INDEX IF NOT EXISTS "StaffInvite_businessId_email_pending_uniq"
  ON "StaffInvite"("businessId", "email")
  WHERE "status" = 'PENDING' AND "email" IS NOT NULL;

-- Note: LoyaltyTransaction.refundSourceId and LoyaltyTransaction.expirySourceId
-- already carry a unique constraint generated by Prisma's @unique directive.
-- Adding a second UNIQUE constraint on the same column would be redundant and
-- rejected by PostgreSQL. The existing constraints already prevent double-refund
-- and double-expiry at the database level.
