-- prisma-migrate-no-transaction
-- Composite indexes for high-cardinality queries

CREATE INDEX CONCURRENTLY IF NOT EXISTS "Membership_businessId_isActive_idx"
  ON "Membership"("businessId", "isActive");

CREATE INDEX CONCURRENTLY IF NOT EXISTS "LoyaltyTransaction_businessId_membershipId_idx"
  ON "LoyaltyTransaction"("businessId", "membershipId");

CREATE INDEX CONCURRENTLY IF NOT EXISTS "StaffMember_businessId_idx"
  ON "StaffMember"("businessId");

CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "StaffInvite_businessId_email_pending_uniq"
  ON "StaffInvite"("businessId", "email")
  WHERE "status" = 'PENDING' AND "email" IS NOT NULL;

-- Note: LoyaltyTransaction.refundSourceId and LoyaltyTransaction.expirySourceId
-- already carry a unique constraint generated by Prisma's @unique directive.
-- Adding a second UNIQUE constraint on the same column would be redundant and
-- rejected by PostgreSQL. The existing constraints already prevent double-refund
-- and double-expiry at the database level.
